### ISSUE TITLE
HOC API?

### ISSUE THREAD

**Issue by JelF** [akxcv/vuera#1]
It would be nice

```
const ReactComponent = VueToReact(VueComponent)
// or
const VueComponent = ReactToVue(ReactComponent)
```

**Comment by akxcv** [comment]
Yeah, I'll likely implement that eventually. It's just not that high on my todo list.

**Comment by JelF** [comment]
> @akxcv removed the good first issue label 8 hours ago
:(((((((((

**Comment by akxcv** [comment]
> :(((((((((

Wha?
