### ISSUE TITLE
React-native

### ISSUE THREAD

**Issue by JafarAkhondali** [akxcv/vuera#11]
Hi,
Is it possible to use React native with Vue? There were no information about this in readme

**Comment by akxcv** [comment]
I don’t think it’s a good idea, not right now. You can read about it in the official Vue guide here: https://vuejs.org/v2/guide/comparison.html#Native-Rendering
Please let me know if that answers your question.

**Comment by JafarAkhondali** [comment]
@akxcv Thanks, I know about Weex and NativeScript, That's why i asked this question. Since Vue has some advantages in speed and ease but lacks in native support in mobile devices, It it possible to use react native in vue?

**Comment by akxcv** [comment]
I don’t know. I never tried Vue for native development, and I seldom tried React Native.
Anyways, vuera currently only supports DOM rendering.
If you wish, you can tackle this question. That would be really cool!

**Comment by akxcv** [comment]
Okay, I'll close this, for now, feel free to reopen if needed.
