### ISSUE TITLE
vue transition warning

### ISSUE THREAD

**Issue by safarishi** [akxcv/vuera#12]
When I use React in vue it works but have a waning with vue

```
[Vue warn]: Unknown custom element:
<transition> - did you register the component correctly? For recursive components,
make sure to provide the "name" option.
```

Because I use transition compoent in my vue app

Then I try to remove transition component in vue app, the warning is disappeared

**Comment by akxcv** [comment]
As far as I can tell, this is not an issue with vuera. Did you figure it out?
