### ISSUE TITLE
How to transform Vue events in React?

### ISSUE THREAD

**Issue by e1emeb0t** [akxcv/vuera#14]
In Vue, we can use `v-on:click` directive, and in React it can be `onClick`. If I want to embed Vue components in React, how can I bind `click` event to them?

**Comment by akxcv** [comment]
When you want to bind events like `onClick`, you have to bind them to DOM elements. In case of React components, that would be the in-built React components like `div`, `span`, `a`...
So, in your case:
```vue
// VueComponent.vue
<template>
  <my-react-component @click="handleClick" />
</template>
<script>
  export default {
    methods: {
      handleClick (e) {
        // ...
      }
    }
  }
</script>
```
```jsx
// ReactComponent.js
import React from 'react'
export default ({ click }) => <a href='#' onClick={click} />
```
Something like that. Did this off the top of my head, feel free to ask further questions.

**Comment by e1emeb0t** [comment]
Thanks for your response, actually I'm embedding Vue components into React project, and Vue components are from third party, I can't modify its source code but apply `props`.

```js
/*
  import from Vue components, its common usage is:
  <el-button v-on:click="console.log">click working here<el-button>
*/

import { Button } from 'element-ui';

export default () => (
  <Button onClick={console.log}>click not working here</Button>
)
```

**Comment by akxcv** [comment]
You can't put event handlers on React components that are not in-built (DOM) components. In your case, you could wrap your `Button` component in an `a`:
```jsx
import { Button } from 'element-ui'

export default () => (
  <a onClick={console.log}>
    <Button>text</Button>
  </a>
)
```

About `v-model`: I actually didn't think about it! Currently, you'd need to pass an updater function along with the current value (like you would do with React inputs). Maybe there's a way to make this more convenient in Vuera. If you have any ideas about that, please tell me! And, please create a separate issue about `v-model` if you don't mind.

**Comment by e1emeb0t** [comment]
I found `value` prop works as one-way binding, currently to make `v-model` and `v-on` directives work as expected, I need create a Vue wrapper to expose on* events like `value`, `onChange` and `onClick`.

BTW, thanks for `vuera`, I was thinking about cooking a library like yours, it's awesome.

**Comment by akxcv** [comment]
Yeah, directives don't work on React elements at all as of now. We could possibly support them, but I'll have to think about it.
Closing this for now, feel free to reopen if needed.

**Comment by tujoworker** [comment]
Here is an **example**: https://github.com/tujoworker/example-vue

**Comment by akxcv** [comment]
@tujoworker is this what you're trying to do?
```
<dnb-button text="My Button 2" v-on:click="greet"  />
```

**Comment by tujoworker** [comment]
Thanks for Your reply @akxcv ☺️
Yes, and also with `@click`:

```jsx
<dnb-button text="My Button 1" @click="handleClick" />
```

**Comment by akxcv** [comment]
I cloned your repo and messed around for a bit. It seems that JSX is not properly configured. I rewrote `ReactButton` to use plain `React.createElement` statements without any JSX and everything worked fine.

**Comment by tujoworker** [comment]
Thank You @akxcv ♥️
