### ISSUE TITLE
Unknown custom element router-view

### ISSUE THREAD

**Issue by josephrexme** [akxcv/vuera#18]
I have Vuera loaded in the same file as my vue router but when I mount vuera it affects vue-router. Here's my router file:

```js
import Vue from 'vue'
import Router from 'vue-router'
import { VuePlugin } from 'vuera'
import Home from '@/components/Home'

Vue.use(VuePlugin)
Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home
    }
  ]
})
```
when I take out the 3rd and 6th line with Vuera/VuePlugin, the app works again. Here's the error I get:

```
Unknown custom element: <router-view>
```

**Comment by js2017** [comment]
Same issue.

**Comment by akxcv** [comment]
Thanks for reporting the issue! Hmm, I'll have to take a look into internals of VueRouter. I'll get back to you once I do that.

**Comment by akxcv** [comment]
I did some investigation and found out that there’s some bug in my Vue plugin that breaks globally registered Vue components. Will fix ASAP.

**Comment by akxcv** [comment]
Fixed! The bug should be gone in Vuera 0.1.3.
Sorry for taking so long, got too much work currently :(

**Comment by josephrexme** [comment]
Understood. Appreciate your quick update on the issue. Thanks!!

**Comment by josephrexme** [comment]
FYI, I wrote about this here https://x-team.com/blog/react-vue-component-integration/

**Comment by akxcv** [comment]
That's a nice blog post @josephrexme!

**Comment by akxcv** [comment]
Do you mind if I add a link to you article to Vuera’s README @josephrexme?

**Comment by josephrexme** [comment]
I'll be glad to have that. I don't mind at all
