### ISSUE TITLE
Using antd in Vue, antd has no style, ask the style how to take effect

### ISSUE THREAD

**Issue by huoxiangdong** [akxcv/vuera#32]
React frameworks like antd,  in Vue, and how to style import

**Comment by akxcv** [comment]
Hi, can you please provide a code example? Or describe your issue in more detail? I'm having trouble comprehending what you mean.

**Comment by akxcv** [comment]
Closed because of inactivity.

**Comment by TAUnionEd** [comment]
Simple resolution:
```
import { Table } from 'antd';
import 'antd/lib/table/style';
```

I think babel can do it automatically, but I can't find the way
