### ISSUE TITLE
Parse error using vue in react

### ISSUE THREAD

**Issue by marceloavf** [akxcv/vuera#42]
## Bug Report

**Describe the bug**

After including 'vuera/babel' in babel-loader plugins it start giving some errors in react parse.
Is there any exception in `vue` or `vue-loader` version for support ?

Thanks!

Console error:
```
Uncaught TypeError: Cannot read property 'constructor' of undefined
    at isReactComponent (vuera.cjs.js?ea64:410)
    at babelReactResolver$$1 (vuera.cjs.js?ea64:475)
    at ProxyComponent.render (root.jsx?1914:29)
    at ProxyComponent.hotComponentRender (react-hot-loader.development.js?ba54:622)
    at ProxyComponent.proxiedRender (react-hot-loader.development.js?ba54:630)
    at finishClassComponent (react-dom.development.js?61bb:13193)
    at updateClassComponent (react-dom.development.js?61bb:13155)
    at beginWork (react-dom.development.js?61bb:13824)
    at performUnitOfWork (react-dom.development.js?61bb:15863)
    at workLoop (react-dom.development.js?61bb:15902)

The above error occurred in the <Root> component:
    in Root
    in AppContainer
    in HotExportedRoot

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

**Code reference**
https://github.com/pedronauck/docz/pull/50

**Environment**

* Node/npm version: Node v9.11.2/npm 6.0.0

**Comment by akxcv** [comment]
Hi! I would love to help, but I'm having trouble trying to run the code you provided :(
vuera should work with versions of Vue/Vue-loader you're using. I'll try running your code again later. Meanwhile, if you get more insight into the issue, please let me know.

**Comment by marceloavf** [comment]
Thanks for answering back @akxcv, you can debug by run this commands in order, starting in the root folder
```shell
$ yarn install
$ yarn bs
$ yarn packages
$ cd examples/vue
$ yarn dev --debug
```
Then in the localhost:3000 you will see these errors in the console.
With this code we are trying to implement the `docz-plugin-vue` (packages folder) to run vue components inside `.mdx`, some functions called `DoczTheme()` are being parsed by vuera and returning the error that you see above.

I'll let you know if we get something different, thank you again!

**Comment by akxcv** [comment]
Thanks for the detailed explanation! It appears that you've found a bug in vuera. Fixing it now!

**Comment by akxcv** [comment]
Your code appears to work on vuera@0.2.2 I just released. Please feel free to reopen the issue if you have any more troubles.
