### ISSUE TITLE
Event handling issue: Vue app and own React component

### ISSUE THREAD

**Issue by YuraKostin** [akxcv/vuera#45]
Hello. Thanks for the vuera.

I have a Vue application, and I use third party React components from other team, and from [MUI library](https://material-ui.com/).

There is a [Switch component in form](https://material-ui.com/demos/selection-controls/#switches-with-formcontrollabel), here is an example of usage:

```javascript
<FormControlLabel
    control={
        <Switch
            checked={this.state.checkedA}
            onChange={this.handleChange('checkedA')}
            value="checkedA"
        />
    }
    label="Secondary"
/>
```

As far as understand - [I can't pass a component as a property](https://github.com/akxcv/vuera/issues/33), so I have made a wrapped Switch component.

```javascript
import React from 'react';
import { Switch, FormControlLabel } from 'material-ui';

class WrappedSwitch extends React.Component {
    render() {
        return (<FormControlLabel
            control={
                <Switch
                    checked={this.props.isChecked}
                    onChange={this.props.onChange}
                    value={this.props.value}
                />
            }
            label={this.props.labelText}
        />);
    }
}

export default WrappedSwitch;
```

Component is being rendered fine, but `onChange` event doesn't fire.

In Vue component:

```javascript
WrappedSwitch(
    :isChecked="form.isAvail",
    @onChange="handleAvailabilityChange",
    value="isAvailable",
    labelText="Is available",
)
```

What can be done wrong?

Thanks a lot.

**Comment by akxcv** [comment]
Hi! I will try to reproduce your case when I have time, for now, could you please check out [a similar issue](https://github.com/akxcv/vuera/issues/14)?

**Comment by YuraKostin** [comment]
Hello.

I've got brilliant news.

I have installed `@materual-ui/core`, and then changed `import` expressions from `material-ui` to `@material-ui/core` accordingly.
And everything works fine.

**Comment by akxcv** [comment]
Glad that everything is okay!
