### ISSUE TITLE
Usage with webpack error.

### ISSUE THREAD

**Issue by F1ks3r** [akxcv/vuera#5]
Uncaught Error: Module build failed: ReferenceError: Unknown plugin "vuera/babel" specified in "base" at 1, attempted to resolve relative to "C:\\Users\\skrrt\\Desktop\\stuff\\ttn-front\\src".

Tried everything to work with babel-loader through webpack, can't get it to work.

More like a general question, how to set up with webpack?

**Comment by akxcv** [comment]
Yeah, it seems I broke it at some point.

For now, try to specify `vuera/dist/babel.js` instead of `vuera/babel`. I'll get around to fixing this soon.

**Comment by akxcv** [comment]
@F1ks3r Fixed! Please try using the babel plugin according to README in vuera@0.1.1
