### ISSUE TITLE
[Feature] Total conversion of a project React -> Vue or the other way around

### ISSUE THREAD

**Issue by ebellumat** [akxcv/vuera#55]
Is it possible to use the babel plugin `vuera `in the future, convert a React source code to Vue or the other way around? Definitely, not just during use.

**Comment by akxcv** [comment]
Hi! This sounds quite complicated as I don't think you can reliably and completely map React and Vue to one another. Maybe it's possible to some extent, but definitely not with vuera or its babel plugin. You could try to implement a library of your own that would do that!
Closing this for now, but feel free to continue the discussion if you have any thoughts or questions.
