### ISSUE TITLE
Commendation

### ISSUE THREAD

**Issue by adekoyejoakinhanmi** [akxcv/vuera#7]
Hello, I want to praise this. Although I haven't used it yet. I was really excited that someone decided to bridge the gap between Vue and React. Well done 👍 I'd be happen to contribute too.
P.S. apologies for putting this in issues

**Comment by akxcv** [comment]
Hi! Thanks for saying that! There will be some issues to tackle soon enough. In fact, I'm about to open one right now.

**Comment by Geczy** [comment]
Still have no idea what the benefits are lol

**Comment by akxcv** [comment]
@Geczy well, the primary goal of this repo is to simplify migration from one framework/lib to another. You can also use both if you want to, but a big bundle might be a problem. And also, for science.

**Comment by mattbrunetti** [comment]
@adekoyejoakinhanmi I don't think you need to apologize for putting this in an issue.. how else do we let open-source developers know we appreciate their efforts!? :smile:

**Comment by akxcv** [comment]
Alright, closing this, for now, feel free to reopen if needed.

**Comment by 0exp** [comment]
vi cho pacani
