### ISSUE TITLE
Handle component update

### ISSUE THREAD

**Issue by akxcv** [akxcv/vuera#8]
Currently, in both React and Vue wrappers, if the `component` prop is changed, nothing happens. 

Example:
```jsx
import RegisteredUser from './RegisteredUser.vue'
import GuestUser from './GuestUser.vue'

const User = props => {
  const { registered, user } = this.props
  const Component = registered ? RegisteredUser : GuestUser
  return <Component user={user} />
}
```

Or, in Vue:
```vue
<template>
  <div>
    <registered-user v-if="registered" :user="user" />
    <guest-user v-else :user="user" />
  </div>
</template>
<script>
  import RegisteredUser from './RegisteredUser'
  import GuestUser from './GuestUser'

  export default {
    props: ['registered', 'user'],
    components: { RegisteredUser, GuestUser },
  }
</script>
```

We expect the component to change from `RegisteredUser` to `GuestUser` and back when we change the `registered` prop, but this does not happen, because both React and Vue wrappers essentially cache the component upon creation.

This use case is probably not very common, however, this should be handled correctly.

**Comment by akxcv** [comment]
This shouldn't be hard to fix. For the React wrapper, we just need to do the `ReactDOM.render` thing when component prop updates, and for the Vue wrapper, we probably need to do `this.vueInstance.$destroy(true)` and then repeat the `new Vue(...)` step.

**Comment by adekoyejoakinhanmi** [comment]
For Vue, why recreate the Vue Instance,  what about using the `Vue.$updated` hook?

**Comment by akxcv** [comment]
Vue requires you to register all components that you're going to need in advance. And, AFAIK, there's no way to register a new component when the instance is already created.
Normally, in this case, you would register all the components you'll need in advance. But I don't think that's a good idea in the context of this library.

**Comment by akxcv** [comment]
Also: for `ReactInVue` we could probably update the component via `setState` somehow, but then we'd sacrifice the `displayName`. Also, [calling `ReactDOM.render` isn't much slower than doing `setState` on root component](https://twitter.com/dan_abramov/status/691301224541503488).

_The link above says they both have same performance, but, according to my experiments, `setState` is slightly faster (maybe I'm wrong)._

**Comment by blocka** [comment]
> Vue requires you to register all components that you're going to need in advance. And, AFAIK, there's no way to register a new component when the instance is already created.

"Registering" just means that it's added to `this.$options.components`, added in as an instance variable on the component, or added globally with `Vue.component`. 

Not sure if this helps, but you certainly _can_ "register" components at runtime.

**Comment by akxcv** [comment]
@blocka, thank you for your input! This might have actually helped, but we don't only need to register a component at runtime, we also need to change the template at runtime, and I don't think this is possible. But if there's a way, I'm interested :)

**Comment by akxcv** [comment]
Actually, replacing components seems to be possible! https://www.webpackbin.com/bins/-Kvqe-C2J28A5zNfxfri
Thanks a lot, @blocka!

**Comment by MyKrzysiu** [comment]
@akxcv can you update link? This doesn't work.
