### ISSUE TITLE
react in vue: SyntheticEvent doesn't work 

### ISSUE THREAD

**Issue by yangchendoit** [akxcv/vuera#80]
when i use react component in vue, I try like this, but the test method doesn't work
## react componet
![image](https://user-images.githubusercontent.com/27750211/57835031-4aa9a900-77f0-11e9-954a-3a1cbf12d99e.png)

## vue 
![image](https://user-images.githubusercontent.com/27750211/57833667-1a144000-77ed-11e9-9d8a-b61c5750bb23.png)
![image](https://user-images.githubusercontent.com/27750211/57833711-3fa14980-77ed-11e9-87df-9dee8989f5ae.png)
## result
it displays well, but all SyntheticEvent doesn't work, when i click two buttons, the methods don't be triggered
![image](https://user-images.githubusercontent.com/27750211/57835090-6ca32b80-77f0-11e9-90b7-8c646f23ea83.png)

**Comment by akxcv** [comment]
Hi! It seems that you have a mistake in your React component:
```jsx
<button onClick={testM('test')}>click props method</button>
```
should instead be:
```jsx
<button onClick={() => testM('test')}>click props method</button>
```

**Comment by yangchendoit** [comment]
sorry, my fault, but i fix this mistake , it doesn't work either. 
it's very strange, when i  click both of those buttons, the corresponding methods don't be triggered.
not only the testM method from props, but also the testMethod.

thanks for your reply!

**Comment by akxcv** [comment]
I'm trying to reproduce this but cannot so far. Could you provide a minimal example app where this issue arises?

**Comment by yangchendoit** [comment]
I check the dependencies of my project, Find babel-preset-vue-app in them, And it depends on babel-plugin-transform-vue-jsx, i also use babel-plugin-transform-react-jsx in the project, So that creates the above problem

**Comment by akxcv** [comment]
Hmm, maybe it would be helpful to set up an example application in the repo so that people can reference it if they have trouble setting up their app.

**Comment by yangchendoit** [comment]
[https://codesandbox.io/embed/react-in-vue-csubm](https://codesandbox.io/embed/react-in-vue-csubm) this is a simple demo, but in codesandbox, It will give you an error(It doesn't appear locally), and you can do that locally.
