### ISSUE TITLE
Allow the ability to set Vue instance options

### ISSUE THREAD

**Issue by brennj** [akxcv/vuera#82]
Hello.

Cool repo! Thanks for making it. So I wanted to use components which have a dependency on Vue-118n, but as far as I understood, there is no current way to pass plugin information, where an example is:

```
const messages = {
  en: {
    message: {
      hello: 'hello world'
    }
  }
}

const i18n = new VueI18n({
  locale: 'en', // set locale
  messages, // set locale messages
})

new Vue({ i18n }).$mount('#app')
```

The last line being key to the issue, where I don't think I can do that - because in the source code of `wrappers/Vue.js` with the method `createVueInstance`, there is nothing at the moment that allows pushing additional stuff in.

I have made a local solution that I will push, but it could use some input whether it is the right approach in order to help achieve this! Will update when its up.

**Comment by brennj** [comment]
I made the Pull Request here https://github.com/akxcv/vuera/pull/83 but willing to change approach if there is any feedback!

**Comment by akxcv** [comment]
Hello! It seems like vuera is missing some rather essential functionality and it's strange no one has brought this up yet.

Thank you for taking the time to submit a pull request as well! I'll review it right now.

**Comment by Tofandel** [comment]
The rest is working well but looking for this functionality as well for vuetify, the theming is made from the vue options

**Comment by timsayshey** [comment]
@akxcv Any chance we can get this merged in?

**Comment by akxcv** [comment]
Yeah, I'll try to look into it as soon as I can.
